# -*- coding: utf-8 -*-
"""FalseToTrue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MSOh3lqJU5O4NQ8MJoTrW9CMFOu1ACm
"""



!pip install rasterio

from google.colab import drive
drive.mount('/content/drive')

"""## Converting .tif into png

"""

import rasterio
from PIL import Image
import numpy as np
import os

input_dir = "/content/drive/MyDrive/Paired_Image_Batches/false_color_patches"
output_dir = "/content/drive/MyDrive/Paired_Image_Batches/false_color_patches_png"
os.makedirs(output_dir, exist_ok=True)

def normalize_band(band):
    if np.all(np.isnan(band)):
        return np.zeros_like(band, dtype=np.uint8)
    band_min, band_max = np.nanmin(band), np.nanmax(band)
    if band_max - band_min == 0:
        return np.zeros_like(band, dtype=np.uint8)
    band_norm = (255 * (band - band_min) / (band_max - band_min))
    band_norm = np.nan_to_num(band_norm, nan=0.0)
    return band_norm.astype(np.uint8)

for fname in os.listdir(input_dir):
    if fname.endswith(".tif"):
        with rasterio.open(os.path.join(input_dir, fname)) as src:
            img = src.read()  # (C, H, W)

            if img.shape[0] == 1:
                img = normalize_band(img[0])  # (H,W)

            elif img.shape[0] >= 3:
                bands = [normalize_band(img[c]) for c in range(3)]
                img = np.stack(bands, axis=-1)  # (H,W,3)

            else:
                # If image has no usable bands → create black placeholder
                h, w = img.shape[1], img.shape[2]
                img = np.zeros((h, w, 3), dtype=np.uint8)

            out_path = os.path.join(output_dir, fname.replace(".tif", ".png"))
            Image.fromarray(img).save(out_path)

print("Conversion complete with NaN-safe normalization!")

input_dir = "/content/drive/MyDrive/Paired_Image_Batches/true_color_patches"
output_dir = "/content/drive/MyDrive/Paired_Image_Batches/true_color_patches_png"
os.makedirs(output_dir, exist_ok=True)

for fname in os.listdir(input_dir):
    if fname.endswith(".tif"):
        with rasterio.open(os.path.join(input_dir, fname)) as src:
            img = src.read()  # (C, H, W)

            if img.shape[0] == 1:
                img = normalize_band(img[0])  # (H,W)

            elif img.shape[0] >= 3:
                bands = [normalize_band(img[c]) for c in range(3)]
                img = np.stack(bands, axis=-1)  # (H,W,3)

            else:
                # If image has no usable bands → create black placeholder
                h, w = img.shape[1], img.shape[2]
                img = np.zeros((h, w, 3), dtype=np.uint8)

            out_path = os.path.join(output_dir, fname.replace(".tif", ".png"))
            Image.fromarray(img).save(out_path)

print("Conversion complete with NaN-safe normalization!")

!pip install split-folders

# import splitfolders

# splitfolders.ratio('/content/drive/MyDrive/Paired_Image_Batches/image_batches', output="/content/drive/MyDrive/Paired_Image_Batches/splitted_batches", seed=42, ratio=(0.8, 0.2))

!pip install torchvision torch matplotlib pillow tensorflow

import tensorflow as tf
import os

IMG_HEIGHT, IMG_WIDTH = 256, 256

def load_image(input_path, target_path):
    # Read input
    input_img = tf.io.read_file(input_path)
    input_img = tf.image.decode_image(input_img, channels=3)
    input_img.set_shape([None, None, 3])  # <--- FIX: explicitly set shape
    input_img = tf.image.convert_image_dtype(input_img, tf.float32)
    input_img = tf.image.resize(input_img, [IMG_HEIGHT, IMG_WIDTH])

    # Read target
    target_img = tf.io.read_file(target_path)
    target_img = tf.image.decode_image(target_img, channels=3)
    target_img.set_shape([None, None, 3])  # <--- FIX: explicitly set shape
    target_img = tf.image.convert_image_dtype(target_img, tf.float32)
    target_img = tf.image.resize(target_img, [IMG_HEIGHT, IMG_WIDTH])

    # Normalize to [-1,1]
    input_img = (input_img * 2.0) - 1.0
    target_img = (target_img * 2.0) - 1.0
    return input_img, target_img

def load_dataset(input_dir, target_dir, batch_size=4):
    input_files = sorted([os.path.join(input_dir, f) for f in os.listdir(input_dir)])
    target_files = sorted([os.path.join(target_dir, f) for f in os.listdir(target_dir)])
    dataset = tf.data.Dataset.from_tensor_slices((input_files, target_files))
    dataset = dataset.map(lambda x, y: load_image(x, y), num_parallel_calls=tf.data.AUTOTUNE)
    dataset = dataset.shuffle(200).batch(batch_size).prefetch(tf.data.AUTOTUNE)
    return dataset

train_dataset = load_dataset('/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/train/false_color_patches_png', '/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/train/true_color_patches_png')
val_dataset   = load_dataset('/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/false_color_patches_png', '/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/true_color_patches_png')

from tensorflow.keras import layers

def downsample(filters, size, apply_batchnorm=True):
    initializer = tf.random_normal_initializer(0., 0.02)
    result = tf.keras.Sequential()
    result.add(layers.Conv2D(filters, size, strides=2, padding='same',
                             kernel_initializer=initializer, use_bias=False))
    if apply_batchnorm:
        result.add(layers.BatchNormalization())
    result.add(layers.LeakyReLU())
    return result

def upsample(filters, size, apply_dropout=False):
    initializer = tf.random_normal_initializer(0., 0.02)
    result = tf.keras.Sequential()
    result.add(layers.Conv2DTranspose(filters, size, strides=2, padding='same',
                                      kernel_initializer=initializer, use_bias=False))
    result.add(layers.BatchNormalization())
    if apply_dropout:
        result.add(layers.Dropout(0.5))
    result.add(layers.ReLU())
    return result

def Generator():
    inputs = layers.Input(shape=[256,256,3])
    down_stack = [
        downsample(64, 4, apply_batchnorm=False),
        downsample(128, 4),
        downsample(256, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
        downsample(512, 4),
    ]
    up_stack = [
        upsample(512, 4, apply_dropout=True),
        upsample(512, 4, apply_dropout=True),
        upsample(512, 4, apply_dropout=True),
        upsample(512, 4),
        upsample(256, 4),
        upsample(128, 4),
        upsample(64, 4),
    ]
    initializer = tf.random_normal_initializer(0., 0.02)
    last = layers.Conv2DTranspose(3, 4, strides=2, padding='same',
                                  kernel_initializer=initializer,
                                  activation='tanh')
    x = inputs
    skips = []
    for down in down_stack:
        x = down(x)
        skips.append(x)
    skips = reversed(skips[:-1])
    for up, skip in zip(up_stack, skips):
        x = up(x)
        x = layers.Concatenate()([x, skip])
    x = last(x)
    return tf.keras.Model(inputs=inputs, outputs=x)

def Discriminator():
    initializer = tf.random_normal_initializer(0., 0.02)
    inp = layers.Input(shape=[256,256,3], name='input_image')
    tar = layers.Input(shape=[256,256,3], name='target_image')
    x = layers.concatenate([inp, tar])
    down1 = downsample(64, 4, False)(x)
    down2 = downsample(128, 4)(down1)
    down3 = downsample(256, 4)(down2)
    zero_pad1 = layers.ZeroPadding2D()(down3)
    conv = layers.Conv2D(512, 4, strides=1,
                         kernel_initializer=initializer,
                         use_bias=False)(zero_pad1)
    batchnorm1 = layers.BatchNormalization()(conv)
    leaky_relu = layers.LeakyReLU()(batchnorm1)
    zero_pad2 = layers.ZeroPadding2D()(leaky_relu)
    last = layers.Conv2D(1, 4, strides=1,
                         kernel_initializer=initializer)(zero_pad2)
    return tf.keras.Model(inputs=[inp, tar], outputs=last)

generator = Generator()
discriminator = Discriminator()

loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def generator_loss(disc_generated_output, gen_output, target):
    gan_loss = loss_object(tf.ones_like(disc_generated_output), disc_generated_output)
    l1_loss = tf.reduce_mean(tf.abs(target - gen_output))
    return gan_loss + (100 * l1_loss)

def discriminator_loss(disc_real_output, disc_generated_output):
    real_loss = loss_object(tf.ones_like(disc_real_output), disc_real_output)
    generated_loss = loss_object(tf.zeros_like(disc_generated_output), disc_generated_output)
    return real_loss + generated_loss

generator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
discriminator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

@tf.function
def train_step(input_image, target):
    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
        gen_output = generator(input_image, training=True)
        disc_real_output = discriminator([input_image, target], training=True)
        disc_generated_output = discriminator([input_image, gen_output], training=True)
        gen_loss = generator_loss(disc_generated_output, gen_output, target)
        disc_loss = discriminator_loss(disc_real_output, disc_generated_output)
    generator_gradients = gen_tape.gradient(gen_loss, generator.trainable_variables)
    discriminator_gradients = disc_tape.gradient(disc_loss, discriminator.trainable_variables)
    generator_optimizer.apply_gradients(zip(generator_gradients, generator.trainable_variables))
    discriminator_optimizer.apply_gradients(zip(discriminator_gradients, discriminator.trainable_variables))
    return gen_loss, disc_loss

import time

EPOCHS = 100

for epoch in range(EPOCHS):
    start = time.time()
    for input_image, target in train_dataset:
        g_loss, d_loss = train_step(input_image, target)
    print(f'Epoch {epoch+1}, Gen Loss: {g_loss.numpy():.4f}, Disc Loss: {d_loss.numpy():.4f}, Time: {time.time()-start:.2f}s')

generator.save("/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/generator.keras")
discriminator.save("/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/discriminator.keras")

generator = tf.keras.models.load_model("/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/generator.keras", compile=False)
discriminator =tf.keras.models.load_model("/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/discriminator.keras", compile=False)

import matplotlib.pyplot as plt
import numpy as np

def generate_and_visualize(generator, dataset, num_examples=3):
    for inp, tar in dataset.take(num_examples):
        # Generate prediction
        pred = generator(inp, training=False)

        # De-normalize from [-1,1] back to [0,1]
        inp = (inp[0] + 1) / 2
        tar = (tar[0] + 1) / 2
        pred = (pred[0] + 1) / 2

        plt.figure(figsize=(15,5))

        titles = ['False-color Input', 'Generated True-color', 'Real True-color']
        images = [inp, pred, tar]

        for i in range(3):
            plt.subplot(1, 3, i+1)
            plt.imshow(images[i])
            plt.title(titles[i])
            plt.axis('off')
        plt.show()

# Call function
generate_and_visualize(generator, val_dataset, num_examples=3)

IMG_HEIGHT, IMG_WIDTH = 256, 256  # same as training

def load_and_preprocess_image(image_path):
    img = tf.io.read_file(image_path)
    img = tf.image.decode_png(img, channels=3)
    img = tf.image.resize(img, [IMG_HEIGHT, IMG_WIDTH])
    img = (img / 127.5) - 1  # normalize to [-1, 1]
    img = tf.expand_dims(img, axis=0)  # add batch dimension
    return img

# Path to your test image (cloudy image)
test_image_path = "/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/false_color_patches_png/Bhopal_false_color_patch_8.png"
test_input = load_and_preprocess_image(test_image_path)

# Predict
prediction = generator(test_input, training=False)
label_image_path = "/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/true_color_patches_png/Bhopal_true_color_patch_8.png"
test_target = load_and_preprocess_image(label_image_path)

import numpy as np
import tensorflow as tf

def denormalize(img):
    img = (img + 1.0) * 127.5  # [-1,1] → [0,255]
    return tf.cast(tf.clip_by_value(img, 0, 255), tf.uint8)

pred_img = denormalize(prediction[0])    # first element of batch
target_img = denormalize(test_target[0]) # first element of batch

psnr = tf.image.psnr(pred_img, target_img, max_val=255)
ssim = tf.image.ssim(pred_img, target_img, max_val=255)

print("PSNR:", psnr.numpy())
print("SSIM:", ssim.numpy())

import os
import random
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score
from skimage.color import rgb2gray

# --- Helper functions ---
def denormalize(img):
    """Convert image from [-1,1] to [0,255]"""
    img = (img + 1.0) * 127.5
    return tf.cast(tf.clip_by_value(img, 0, 255), tf.uint8)

def compute_f1(img1, img2, threshold=127):
    """
    Compute F1 score between two RGB images (convert to grayscale and threshold)
    """
    # Convert to grayscale
    gray1 = rgb2gray(img1 / 255.0)
    gray2 = rgb2gray(img2 / 255.0)
    # Threshold to binary masks
    bin1 = (gray1 * 255 > threshold).astype(np.uint8).flatten()
    bin2 = (gray2 * 255 > threshold).astype(np.uint8).flatten()
    return f1_score(bin2, bin1, zero_division=1)

def evaluate_and_show(generator, test_false_dir, test_true_dir, n=6):
    # Get list of image files
    false_imgs = sorted(os.listdir(test_false_dir))
    true_imgs = sorted(os.listdir(test_true_dir))
    assert len(false_imgs) == len(true_imgs), "False and true image counts must match!"

    # Select n random indices
    idxs = random.sample(range(len(false_imgs)), n)

    for idx in idxs:
        # Paths
        f_path = os.path.join(test_false_dir, false_imgs[idx])
        t_path = os.path.join(test_true_dir, true_imgs[idx])

        # Load and preprocess (must match your training preprocessing)
        inp = load_and_preprocess_image(f_path)       # shape (1,H,W,C), range [-1,1]
        tar = load_and_preprocess_image(t_path)       # shape (1,H,W,C), range [-1,1]

        # Generate
        pred = generator(inp, training=False)

        # Convert to displayable uint8
        inp_img = denormalize(inp[0]).numpy()
        pred_img = denormalize(pred[0]).numpy()
        tar_img = denormalize(tar[0]).numpy()

        # Metrics
        psnr_val = tf.image.psnr(pred_img, tar_img, max_val=255).numpy()
        ssim_val = tf.image.ssim(pred_img, tar_img, max_val=255).numpy()
        f1_val = compute_f1(pred_img, tar_img)

        # --- Show images ---
        plt.figure(figsize=(15,5))
        titles = [
            f"False-color Input\n{false_imgs[idx]}",
            f"Generated True-color\nPSNR={psnr_val:.2f}, SSIM={ssim_val:.3f}, F1={f1_val:.3f}",
            f"Real True-color\n{true_imgs[idx]}"
        ]
        images = [inp_img, pred_img, tar_img]

        for i in range(3):
            plt.subplot(1, 3, i+1)
            plt.imshow(images[i])
            plt.title(titles[i], fontsize=10)
            plt.axis('off')
        plt.show()

# --- Call the evaluation ---
false_color_dir = "/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/false_color_patches_png"
true_color_dir = "/content/drive/MyDrive/Paired_Image_Batches/splitted_batches/val/true_color_patches_png"

evaluate_and_show(generator, false_color_dir, true_color_dir, n=6)

